### ISSUE TITLE
Get Binary to Text working

### ISSUE THREAD

**Issue by notBanii** [SpectrumDevs/Spectrum#8]
It's pretty annoying when someone tries to do that and goes; "AAAAAAAAAAAAAAAAA LAMEEEEEEEEEEE"

**Comment by SpectrixOfficial** [comment]
# AAAAAAAAAAAAAAAAAAAAAAAAAAA

Firstly: _It's not even in this version_, and I'm pretty sure it's never been on this repo
Secondly: **I'm going to be adding all of that now, loads of text converter things**

###### _this isn't even a bug it's just never been a thing, nor is it an issue ;-;_

**Comment by SpectrixOfficial** [comment]
as you can see from above, python is much easier than js.

###### :)

**Comment by notBanii** [comment]
^

**Comment by UbnGithub** [comment]
One lang can't be objectively easier than another.

**Comment by notBanii** [comment]
One lang can't be objectively better than another

**Comment by UbnGithub** [comment]
Ok

**Comment by SpectrixOfficial** [comment]
I'm closing this because it's not even an issue

**Comment by SpectrixOfficial** [comment]
I added it [here](https://github.com/SpectrumDevs/Spectrum/commit/fb21cfbb9bd87e139b664646fdd09a47e1cbc7d8#diff-c0fbcbe38b79fd3b8789d6c36bf11a27). _If there's any **actual problems**, open up another issue_
